apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pesitwizard-server.fullname" . }}-secrets
  labels:
    {{- include "pesitwizard-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  pesit-password: {{ .Values.config.pesit.password | quote }}
  {{- if .Values.config.security }}
  {{- if .Values.config.security.masterKey }}
  master-key: {{ .Values.config.security.masterKey | quote }}
  {{- end }}
  {{- if .Values.config.security.encryptionSalt }}
  encryption-salt: {{ .Values.config.security.encryptionSalt | quote }}
  {{- end }}
  {{- end }}
