{{- if and .Values.tls.enabled (not .Values.tls.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pesitwizard-client.fullname" . }}-tls
  labels:
    {{- include "pesitwizard-client.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
type: Opaque
data:
  # These will be populated by the install script or init container
  # Placeholder values - actual certs should be provided
  {{- if .Values.tls.keystoreData }}
  keystore.p12: {{ .Values.tls.keystoreData | b64enc }}
  {{- end }}
  {{- if .Values.tls.truststoreData }}
  truststore.p12: {{ .Values.tls.truststoreData | b64enc }}
  {{- end }}
stringData:
  keystore-password: {{ .Values.tls.keystorePassword | default "changeit" | quote }}
  truststore-password: {{ .Values.tls.truststorePassword | default "changeit" | quote }}
{{- end }}
